#database secret- credentials are passed here, not hardcoded (security)


# Need to Enable Key Vault provider in AKS for complete encryption 


apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: splitwise
type: Opaque
data:
  username: <base64-encoded>
  password: <base64-encoded>